name = "skynerd-api"
main = "src/index.ts"
compatibility_date = "2025-10-07"

routes = [
  { pattern = "api.skynerd.io/*", zone_name = "skynerd.io" }
]

[vars]
ALLOWED_ORIGINS = "https://skynerd.io,http://localhost:3000"
